### ISSUE TITLE
Broken paperless_auth binary

### ISSUE THREAD

**Issue by p3l1** [CrystalNET-org/paperless-ftpd#10]
Hey there,

it seems like the content of the file `paperless_auth` is only `Not found`, in the latest tag (0.2.3).

When setting up the ftpd service, I had trouble with the authentication and did some digging. When inspecting the running container I found that the required go binary is not correctly built into the image. Its also only 9 bytes.

```
container:/opt/pureftpd/sbin$ ls -al
total 264
drwxr-xr-x    1 root     root          4096 Dec 22  2023 .
drwxr-xr-x    1 root     root          4096 Dec 22  2023 ..
-rw-r--r--    1 root     root             9 Dec 22  2023 paperless_auth
-rwxr-xr-x    1 root     root         22808 Dec 22  2023 pure-authd
-rwxr-xr-x    1 root     root         14096 Dec 22  2023 pure-certd
-rwxr-xr-x    1 root     root        139632 Dec 22  2023 pure-ftpd
-rwxr-xr-x    1 root     root         14096 Dec 22  2023 pure-ftpwho
-rwxr-xr-x    1 root     root         14096 Dec 22  2023 pure-mrtginfo
-rwxr-xr-x    1 root     root         22376 Dec 22  2023 pure-quotacheck
-rwxr-xr-x    1 root     root         14096 Dec 22  2023 pure-uploadscript
```

Would love to use this feature! Thanks for your great work on the paperless helm chart!

**Comment by psych0d0g** [comment]
interesting, ill investigate asap and will report back, thanks for bringing this up :)

**Comment by p3l1** [comment]
Thanks!
It seems like the link to the artifact is outdated.

https://github.com/CrystalNET-org/paperless-ftpd/blob/a41b6b2569b91256430b15667946b476e2ba9532/Dockerfile#L39

**Comment by p3l1** [comment]
Heyho, any news on that?

**Comment by TheBinaryLoop** [comment]
It also looks like the docker image on harbor is also affected from this

**Comment by psych0d0g** [comment]
this issue should be fixed with https://github.com/CrystalNET-org/paperless-ftpd/pull/9
sorry that this took so long but i have ben incredibly busy the last few months..
